pipeline {
    agent any
    stages {
        stage ("git checkout") {
            steps {
                git branch: 'main', url: 'https://github.com/vigneshrepo23/ultimate-cicd-java'
            }
        }
        stage ("build") {
            steps{
                sh "mvn clean package"
            }
        }
    }
}